export default function Head() {
  return (
    <>
      <title>Reserve At Milestone Grill | Open Dine</title>
      <meta content="width=device-width, initial-scale=1" name="description" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://i.ibb.co/NpYfF72/icons8-restaurant-16.png"
      />
    </>
  );
}
