export default function Head() {
  return (
    <>
      <title>Open Dine</title>
      <meta content="width=device-width, initial-scale=1" name="description" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://i.ibb.co/JBC11MQ/open-dinee.png" />
    </>
  );
}
